export const ADD_NEW_TASK = 'addNewTask'
export const SET_NEW_TASK_ID = 'setNewTaskId'
export const UPDATE_TASK_CONTENT = 'updateTaskContent'
export const DELETE_TASK_BY_ID = 'deleteTaskById'
export const UPDATE_TASK_ORDER = 'updateTaskOrder'
export const MOVE_TASK_TO_ANOTER = 'moveTaskToAnother'
